wxFreeChart: LabelAxis Class Reference
LabelAxis Class Reference abstract
Base class for axes for displaying data labels.
#include <labelaxis.h>
Public Member Functions
LabelAxis (AXIS_LOCATION location)
void SetTitle (const wxString &title)
Sets axis title.
const wxString & GetTitle ()
Returns axis title.
void SetTitleLocation (int location)
Sets axis title location.
int GetTitleLocation ()
Returns axis title location.
void SetTitleFont (wxFont &font)
Sets axis title font.
const wxFont & GetTitleFont ()
Returns axis title font.
void SetTitleColour (wxColour &colour)
Sets axis title colour.
wxColour GetTitleColour ()
Returns axis title colour.
void SetLabelPen (wxPen labelPen)
Sets pen for label lines.
void SetLabelTextColour (wxColour labelTextColour)
Sets colour for labels.
wxColour GetLabelTextColour ()
Returns label colour.
void SetLabelTextFont (wxFont labelTextFont)
Sets font for labels text.
const wxFont & GetLabelTextFont ()
Returns label font.
void SetVerticalLabelText (bool verticalLabelText)
Sets whether to draw labels text vertical.
bool GetVerticalLabelText ()
Returns whether to draw labels text vertical.
wxDEPRECATED_MSG ("Use SetMinorIntervalCount instead.") void SetMajorLabelSteps(size_t step)
Sets major label steps.
void SetMinorIntervalCount (size_t count)
Set the number of ticks between each label (major interval).
size_t GetMinorIntervalCout ()
Get the number of ticks between each label (major interval).
void SetLabelSkip (int blankLabels)
int GetLabelSkip ()
void SetLabelColourer (LabelColourer *labelColourer)
LabelColourer * GetLabelColourer ()
void SetAxisVisible (bool bVisible)
Sets visibility of axis.
virtual void Draw (wxDC &dc, wxRect rc)
Performs axis drawing.
virtual void DrawGridLines (wxDC &dc, wxRect rc)
Draws grid lines for axis.
virtual wxCoord GetExtent (wxDC &dc)
Used to determine minimal size needed to draw axis contents, minimal width for vertical axes, minimal height for horizontal.
Public Member Functions inherited from Axis
Axis (AXIS_LOCATION location)
Constructs new axis.
AXIS_LOCATION GetLocation ()
Returns axis location.
bool IsVertical ()
Checks whether axis is vertical.
bool IsHorizontal ()
Checks whether axis is horizontal.
void SetMargins (wxCoord marginMin, wxCoord marginMax)
Sets minimal/maximal margins for axis.
void SetMajorGridlinePen (const wxPen &pen)
Sets the pen to be used for drawing major gridlines.
void SetMinorGridlinePen (const wxPen &pen)
Sets the pen to be used for drawing minor gridlines.
const wxPen & GetMajorGridlinePen ()
Gets the pen that is currently used to draw major gridlines on this axis.
const wxPen & GetMinorGridlinePen ()
Gets the pen that is currently used to draw minor gridlines on this axis.
size_t GetDatasetCount ()
Returns dataset counts, linked with this axis.
Dataset * GetDataset (size_t index)
Returns dataset, linked with this axis at specified index.
void SetZoomPanMode ()
void SetWindowWidth (double winWidth)
Sets window width.
double GetWindowWidth ()
Returns window width.
void SetWindowPosition (double winPos)
Sets window position.
double GetWindowPosition ()
Returns window position.
void SetUseWindow (bool useWin)
Sets whether to use window.
void SetWindow (double winPos, double winWidth)
Sets window params (position and width).
bool IntersectsWindow (double v0, double v1)
Checks whether line in data space intersects window.
void GetWindowBounds (double &winMin, double &winMax)
Returns window bounds.
void AddDataset (Dataset *dataset)
internal.
virtual void GetDataBounds (double &minValue, double &maxValue) const =0
Returns data bounds.
virtual bool IsVisible (double value)
Checks whether data value is visible.
virtual double BoundValue (double value)
Returns nearest boundary value.
virtual wxCoord ToGraphics (wxDC &dc, int minCoord, int gRange, double value)
Transforms coordinate from data space to graphics space.
virtual double ToData (wxDC &dc, int minCoord, int gRange, wxCoord g)
Transforms coordinate from graphics space to data space.
virtual bool UpdateBounds ()=0
Performs axis bounds update after dataset/s change.
Public Member Functions inherited from Observable< AxisObserver >
void AddObserver (AxisObserver *_observer)
void RemoveObserver (AxisObserver *_observer)
Protected Member Functions
virtual double GetValue (size_t step)=0
Returns value on step.
virtual void GetLabel (size_t step, wxString &label)=0
Returns label on step.
virtual bool IsEnd (size_t step)=0
Check whether step is last.
virtual wxSize GetLongestLabelExtent (wxDC &dc)=0
virtual bool HasLabels ()
Protected Member Functions inherited from Axis
virtual bool AcceptDataset (Dataset *dataset)=0
Checks whether dataset can be accepted by this axis.
FIRE_WITH_THIS (AxisChanged)
FIRE_WITH_THIS (BoundsChanged)
Additional Inherited Members
Public Types inherited from Observable< AxisObserver >
typedef AxisObserver Observer
Public Attributes inherited from Observable< AxisObserver >
std::vector< AxisObserver * >::iterator OIt
Protected Attributes inherited from Axis
DatasetArray m_datasets
wxPen m_majorGridlinePen
wxPen m_minorGridlinePen
wxCoord m_marginMin
wxCoord m_marginMax
double m_winPos
double m_winWidth
bool m_useWin
Protected Attributes inherited from Observable< AxisObserver >
std::vector< AxisObserver * > observers
Detailed Description
Base class for axes for displaying data labels.
Definition at line 29 of file labelaxis.h.
Member Function Documentation
virtual void LabelAxis::Draw (wxDC & dc, wxRect rc) virtual
Performs axis drawing.
Parameters
dc device context
rc rectangle where to draw
Implements Axis.
virtual void LabelAxis::DrawGridLines (wxDC & dc, wxRect rcData) virtual
Draws grid lines for axis.
Parameters
dc device context
rc data area rectangle of plot
Implements Axis.
virtual wxCoord LabelAxis::GetExtent (wxDC & dc) virtual
Used to determine minimal size needed to draw axis contents, minimal width for vertical axes, minimal height for horizontal.
Parameters
dc device context
Returns
extent
Implements Axis.
virtual void LabelAxis::GetLabel (size_t step, wxString & label) protected pure virtual
Returns label on step.
Parameters
step step index
label output label
Implemented in NumberAxis, LogarithmicNumberAxis, DateAxis, CategoryAxis, and JulianDateAxis.
Referenced by NumberAxis::ForceExtraMajorInterval(), and DateAxis::SetDateFormat().
wxColour LabelAxis::GetLabelTextColour () inline
Returns label colour.
Returns
label colour
Definition at line 142 of file labelaxis.h.
const wxFont& LabelAxis::GetLabelTextFont () inline
Returns label font.
Returns
label font
Definition at line 161 of file labelaxis.h.
size_t LabelAxis::GetMinorIntervalCout () inline
Get the number of ticks between each label (major interval).
Returns
The number of minor interval ticks that appear between each major interval label.
Definition at line 214 of file labelaxis.h.
References Axis::Draw(), Axis::DrawGridLines(), and Axis::GetExtent().
const wxString& LabelAxis::GetTitle () inline
Returns axis title.
Returns
axis title
Definition at line 50 of file labelaxis.h.
wxColour LabelAxis::GetTitleColour () inline
Returns axis title colour.
Returns
axis title colour
Definition at line 113 of file labelaxis.h.
const wxFont& LabelAxis::GetTitleFont () inline
Returns axis title font.
Returns
axis title font
Definition at line 92 of file labelaxis.h.
int LabelAxis::GetTitleLocation () inline
Returns axis title location.
Returns
axis title location
Definition at line 73 of file labelaxis.h.
virtual double LabelAxis::GetValue (size_t step) protected pure virtual
Returns value on step.
Parameters
step step index
Returns
value on step
Implemented in NumberAxis, LogarithmicNumberAxis, DateAxis, and CategoryAxis.
Referenced by NumberAxis::ForceExtraMajorInterval(), and DateAxis::SetDateFormat().
bool LabelAxis::GetVerticalLabelText () inline
Returns whether to draw labels text vertical.
Returns
true if labels text will be drawn vertical
Definition at line 182 of file labelaxis.h.
virtual bool LabelAxis::IsEnd (size_t step) protected pure virtual
Check whether step is last.
Parameters
step step
Returns
true if step is last
Implemented in NumberAxis, DateAxis, and CategoryAxis.
Referenced by NumberAxis::ForceExtraMajorInterval(), and DateAxis::SetDateFormat().
void LabelAxis::SetAxisVisible (bool bVisible)
Sets visibility of axis.
Parameters
bVisible - false if hidden
void LabelAxis::SetLabelPen (wxPen labelPen) inline
Sets pen for label lines.
Parameters
labelPen pen for label lines
Definition at line 122 of file labelaxis.h.
void LabelAxis::SetLabelTextColour (wxColour labelTextColour) inline
Sets colour for labels.
Parameters
labelColour color for labels
Definition at line 132 of file labelaxis.h.
void LabelAxis::SetLabelTextFont (wxFont labelTextFont) inline
Sets font for labels text.
Parameters
labelFont font for labels text
Definition at line 151 of file labelaxis.h.
void LabelAxis::SetMinorIntervalCount (size_t count) inline
Set the number of ticks between each label (major interval).
Parameters
count The number of minor interval ticks that should appear between each major interval label.
Definition at line 204 of file labelaxis.h.
void LabelAxis::SetTitle (const wxString & title) inline
Sets axis title.
Parameters
new axis title
Definition at line 40 of file labelaxis.h.
void LabelAxis::SetTitleColour (wxColour & colour) inline
Sets axis title colour.
Parameters
new axis title colour
Definition at line 101 of file labelaxis.h.
void LabelAxis::SetTitleFont (wxFont & font) inline
Sets axis title font.
Parameters
axis title font
Definition at line 82 of file labelaxis.h.
void LabelAxis::SetTitleLocation (int location) inline
Sets axis title location.
Parameters
location new location for axis title, acceptable values wxLEFT, wxCENTER, wxRIGHT for horizontal axes, wxTOP, wxCENTER, wxBOTTOM for vertical axes.
Definition at line 61 of file labelaxis.h.
void LabelAxis::SetVerticalLabelText (bool verticalLabelText) inline
Sets whether to draw labels text vertical.
Parameters
verticalLabelText true to draw labels text vertical
Definition at line 170 of file labelaxis.h.
LabelAxis::wxDEPRECATED_MSG ("Use SetMinorIntervalCount instead.") inline
Sets major label steps.
Parameters
step The step size at which major label should be drawn
Definition at line 191 of file labelaxis.h.
Referenced by NumberAxis::SetTickFormat().
The documentation for this class was generated from the following file:
include/wx/axis/labelaxis.h