wxFreeChart: AxisShare Class Reference
AxisShare Class Reference
Used to combine axes.
#include <axis.h>
Public Member Functions
AxisShare (Axis *axis)
void SetShareVisible (bool shareVisible)
Sets axis share visible or not.
virtual void GetDataBounds (double &minValue, double &maxValue) const
Returns data bounds.
virtual wxCoord GetExtent (wxDC &dc)
Used to determine minimal size needed to draw axis contents, minimal width for vertical axes, minimal height for horizontal.
virtual bool IsVisible (double value)
Checks whether data value is visible.
virtual double BoundValue (double value)
Returns nearest boundary value.
virtual wxCoord ToGraphics (wxDC &dc, int minCoord, int gRange, double value)
Transforms coordinate from data space to graphics space.
virtual double ToData (wxDC &dc, int minCoord, int gRange, wxCoord g)
Transforms coordinate from graphics space to data space.
virtual bool UpdateBounds () wxOVERRIDE
Performs axis bounds update after dataset/s change.
virtual void Draw (wxDC &dc, wxRect rc)
Performs axis drawing.
virtual void DrawGridLines (wxDC &dc, wxRect rcData)
Draws grid lines for axis.
Public Member Functions inherited from Axis
Axis (AXIS_LOCATION location)
Constructs new axis.
AXIS_LOCATION GetLocation ()
Returns axis location.
bool IsVertical ()
Checks whether axis is vertical.
bool IsHorizontal ()
Checks whether axis is horizontal.
void SetMargins (wxCoord marginMin, wxCoord marginMax)
Sets minimal/maximal margins for axis.
void SetMajorGridlinePen (const wxPen &pen)
Sets the pen to be used for drawing major gridlines.
void SetMinorGridlinePen (const wxPen &pen)
Sets the pen to be used for drawing minor gridlines.
const wxPen & GetMajorGridlinePen ()
Gets the pen that is currently used to draw major gridlines on this axis.
const wxPen & GetMinorGridlinePen ()
Gets the pen that is currently used to draw minor gridlines on this axis.
size_t GetDatasetCount ()
Returns dataset counts, linked with this axis.
Dataset * GetDataset (size_t index)
Returns dataset, linked with this axis at specified index.
void SetZoomPanMode ()
void SetWindowWidth (double winWidth)
Sets window width.
double GetWindowWidth ()
Returns window width.
void SetWindowPosition (double winPos)
Sets window position.
double GetWindowPosition ()
Returns window position.
void SetUseWindow (bool useWin)
Sets whether to use window.
void SetWindow (double winPos, double winWidth)
Sets window params (position and width).
bool IntersectsWindow (double v0, double v1)
Checks whether line in data space intersects window.
void GetWindowBounds (double &winMin, double &winMax)
Returns window bounds.
void AddDataset (Dataset *dataset)
internal.
Protected Member Functions
virtual bool AcceptDataset (Dataset *dataset)
Checks whether dataset can be accepted by this axis.
Additional Inherited Members
Protected Attributes inherited from Axis
DatasetArray m_datasets
wxPen m_majorGridlinePen
wxPen m_minorGridlinePen
wxCoord m_marginMin
wxCoord m_marginMax
double m_winPos
double m_winWidth
bool m_useWin
Detailed Description
Used to combine axes.
Shares axis between plots.
Definition at line 351 of file axis.h.
Member Function Documentation
virtual bool AxisShare::AcceptDataset (Dataset * dataset) protected virtual
Checks whether dataset can be accepted by this axis.
Must be implemented by derivative classes. XXX: maybe remove this method later.
Parameters
dataset dataset to be checked
Returns
true - if dataset can be accepted, false overwise
Implements Axis.
Referenced by Axis::AddDataset().
virtual double AxisShare::BoundValue (double value) virtual
Returns nearest boundary value.
Parameters
value out of bounds value, for which will be returned boundary value
Returns
nearest boundary value
Reimplemented from Axis.
Referenced by Axis::AddDataset().
virtual void AxisShare::Draw (wxDC & dc, wxRect rc) virtual
Performs axis drawing.
Parameters
dc device context
rc rectangle where to draw
Implements Axis.
Referenced by Axis::AddDataset().
virtual void AxisShare::DrawGridLines (wxDC & dc, wxRect rcData) virtual
Draws grid lines for axis.
Parameters
dc device context
rc data area rectangle of plot
Implements Axis.
Referenced by Axis::AddDataset().
virtual void AxisShare::GetDataBounds (double & minValue, double & maxValue) const virtual
Returns data bounds.
Parameters
minValue output minimal data value
maxValue output maximal data value
Implements Axis.
Referenced by Axis::AddDataset(), and Axis::GetWindowBounds().
virtual wxCoord AxisShare::GetExtent (wxDC & dc) virtual
Used to determine minimal size needed to draw axis contents, minimal width for vertical axes, minimal height for horizontal.
Parameters
dc device context
Returns
extent
Implements Axis.
Referenced by Axis::AddDataset().
virtual bool AxisShare::IsVisible (double value) virtual
Checks whether data value is visible.
Parameters
value value in data space
Returns
true if data value is visible
Reimplemented from Axis.
Referenced by Axis::AddDataset().
void AxisShare::SetShareVisible (bool shareVisible)
Sets axis share visible or not.
Note: by default axis share is invisible.
Parameters
shareVisible true to set share visible
virtual double AxisShare::ToData (wxDC & dc, int minCoord, int gRange, wxCoord g) virtual
Transforms coordinate from graphics space to data space.
Parameters
dc device context
minCoord minimal graphics space coordinate
gRange graphics space range
value value in data space
Returns
coordinate in data space
Reimplemented from Axis.
Referenced by Axis::AddDataset().
virtual wxCoord AxisShare::ToGraphics (wxDC & dc, int minCoord, int gRange, double value) virtual
Transforms coordinate from data space to graphics space.
Parameters
dc device context
minCoord minimal graphics space coordinate
gRange graphics space range
value value in data space
Returns
value in graphics space
Reimplemented from Axis.
Referenced by Axis::AddDataset().
The documentation for this class was generated from the following file:
include/wx/axis/axis.h