wxFreeChart: Axis Class Reference
Axis Class Reference abstract
Base class for all axes.
#include <axis.h>
Public Member Functions
Axis (AXIS_LOCATION location)
Constructs new axis.
AXIS_LOCATION GetLocation ()
Returns axis location.
bool IsVertical ()
Checks whether axis is vertical.
bool IsHorizontal ()
Checks whether axis is horizontal.
void SetMargins (wxCoord marginMin, wxCoord marginMax)
Sets minimal/maximal margins for axis.
void SetMajorGridlinePen (const wxPen &pen)
Sets the pen to be used for drawing major gridlines.
void SetMinorGridlinePen (const wxPen &pen)
Sets the pen to be used for drawing minor gridlines.
const wxPen & GetMajorGridlinePen ()
Gets the pen that is currently used to draw major gridlines on this axis.
const wxPen & GetMinorGridlinePen ()
Gets the pen that is currently used to draw minor gridlines on this axis.
size_t GetDatasetCount ()
Returns dataset counts, linked with this axis.
Dataset * GetDataset (size_t index)
Returns dataset, linked with this axis at specified index.
void SetZoomPanMode ()
void SetWindowWidth (double winWidth)
Sets window width.
double GetWindowWidth ()
Returns window width.
void SetWindowPosition (double winPos)
Sets window position.
double GetWindowPosition ()
Returns window position.
void SetUseWindow (bool useWin)
Sets whether to use window.
void SetWindow (double winPos, double winWidth)
Sets window params (position and width).
bool IntersectsWindow (double v0, double v1)
Checks whether line in data space intersects window.
void GetWindowBounds (double &winMin, double &winMax)
Returns window bounds.
void AddDataset (Dataset *dataset)
internal.
virtual void GetDataBounds (double &minValue, double &maxValue) const =0
Returns data bounds.
virtual wxCoord GetExtent (wxDC &dc)=0
Used to determine minimal size needed to draw axis contents, minimal width for vertical axes, minimal height for horizontal.
virtual bool IsVisible (double value)
Checks whether data value is visible.
virtual double BoundValue (double value)
Returns nearest boundary value.
virtual wxCoord ToGraphics (wxDC &dc, int minCoord, int gRange, double value)
Transforms coordinate from data space to graphics space.
virtual double ToData (wxDC &dc, int minCoord, int gRange, wxCoord g)
Transforms coordinate from graphics space to data space.
virtual bool UpdateBounds ()=0
Performs axis bounds update after dataset/s change.
virtual void Draw (wxDC &dc, wxRect rc)=0
Performs axis drawing.
virtual void DrawGridLines (wxDC &dc, wxRect rcData)=0
Draws grid lines for axis.
Protected Member Functions
virtual bool AcceptDataset (Dataset *dataset)=0
Checks whether dataset can be accepted by this axis.
Protected Attributes
DatasetArray m_datasets
wxPen m_majorGridlinePen
wxPen m_minorGridlinePen
wxCoord m_marginMin
wxCoord m_marginMax
double m_winPos
double m_winWidth
bool m_useWin
Friends
class Plot
class AxisShare
Detailed Description
Base class for all axes.
Axis has following attributes:
Location - where axis arranged on plot, can be: AXIS_LEFT, AXIS_RIGHT, AXIS_TOP, AXIS_BOTTOM.
Margins - distance from plot edges to axis labels.
Window - visible subset of data. Window has width and position. Width means how much data points is visible at once, position is first data item visible.
Definition at line 39 of file axis.h.
Constructor & Destructor Documentation
Axis::Axis (AXIS_LOCATION location)
Constructs new axis.
Parameters
location axis location (cannot be changed after axis created)
Member Function Documentation
virtual bool Axis::AcceptDataset (Dataset * dataset) protected pure virtual
Checks whether dataset can be accepted by this axis.
Must be implemented by derivative classes. XXX: maybe remove this method later.
Parameters
dataset dataset to be checked
Returns
true - if dataset can be accepted, false overwise
Implemented in AxisShare, NumberAxis, CompDateAxis, DateAxis, and CategoryAxis.
Referenced by NumberAxis::ForceExtraMajorInterval(), DateAxis::SetDateFormat(), and CompDateAxis::SetSpanDraw().
void Axis::AddDataset (Dataset * dataset) inline
internal.
Don't use from programs.
Definition at line 243 of file axis.h.
References AxisShare::AcceptDataset(), AxisShare::BoundValue(), AxisShare::Draw(), AxisShare::DrawGridLines(), AxisShare::GetDataBounds(), AxisShare::GetExtent(), AxisShare::IsVisible(), AxisShare::ToData(), AxisShare::ToGraphics(), and AxisShare::UpdateBounds().
virtual double Axis::BoundValue (double value) virtual
Returns nearest boundary value.
Parameters
value out of bounds value, for which will be returned boundary value
Returns
nearest boundary value
Reimplemented in AxisShare, and LogarithmicNumberAxis.
virtual void Axis::Draw (wxDC & dc, wxRect rc) pure virtual
Performs axis drawing.
Parameters
dc device context
rc rectangle where to draw
Implemented in AxisShare, LabelAxis, and CompDateAxis.
Referenced by LabelAxis::GetMinorIntervalCout().
virtual void Axis::DrawGridLines (wxDC & dc, wxRect rcData) pure virtual
Draws grid lines for axis.
Parameters
dc device context
rc data area rectangle of plot
Implemented in AxisShare, LabelAxis, and CompDateAxis.
Referenced by LabelAxis::GetMinorIntervalCout().
virtual void Axis::GetDataBounds (double & minValue, double & maxValue) const pure virtual
Returns data bounds.
Parameters
minValue output minimal data value
maxValue output maximal data value
Implemented in AxisShare, NumberAxis, CompDateAxis, DateAxis, and CategoryAxis.
Referenced by NumberAxis::ForceExtraMajorInterval(), and DateAxis::SetDateFormat().
Dataset* Axis::GetDataset (size_t index)
Returns dataset, linked with this axis at specified index.
Parameters
index dataset index
Returns
dataset at index
Referenced by AxisPlot::GetAxisDataset(), and GetMinorGridlinePen().
size_t Axis::GetDatasetCount ()
Returns dataset counts, linked with this axis.
Returns
dataset counts, linked with this axis
Referenced by GetMinorGridlinePen().
virtual wxCoord Axis::GetExtent (wxDC & dc) pure virtual
Used to determine minimal size needed to draw axis contents, minimal width for vertical axes, minimal height for horizontal.
Parameters
dc device context
Returns
extent
Implemented in AxisShare, LabelAxis, and CompDateAxis.
Referenced by LabelAxis::GetMinorIntervalCout().
AXIS_LOCATION Axis::GetLocation () inline
Returns axis location.
Returns
axis location
Definition at line 57 of file axis.h.
const wxPen& Axis::GetMajorGridlinePen () inline
Gets the pen that is currently used to draw major gridlines on this axis.
Returns
The pen currently used to draw major gridlines.
Definition at line 112 of file axis.h.
const wxPen& Axis::GetMinorGridlinePen () inline
Gets the pen that is currently used to draw minor gridlines on this axis.
Returns
The pen currently used to draw minor gridlines.
Definition at line 121 of file axis.h.
References GetDataset(), and GetDatasetCount().
void Axis::GetWindowBounds (double & winMin, double & winMax) inline
Returns window bounds.
If window is not used, simply returns data bounds.
Parameters
winMin out for window minimal
winMax out for window maximal
Definition at line 225 of file axis.h.
References AxisShare::GetDataBounds().
double Axis::GetWindowPosition () inline
Returns window position.
Returns
window position
Definition at line 182 of file axis.h.
double Axis::GetWindowWidth () inline
Returns window width.
Returns
window width
Definition at line 164 of file axis.h.
bool Axis::IntersectsWindow (double v0, double v1)
Checks whether line in data space intersects window.
Parameters
v0 line begin in data space
v0 line end in data space
Returns
true if line intersects window
Referenced by SetWindow().
bool Axis::IsHorizontal () inline
Checks whether axis is horizontal.
Returns
true if axis is horizontal, false - overwise
Definition at line 75 of file axis.h.
References IsVertical(), and SetMargins().
bool Axis::IsVertical () inline
Checks whether axis is vertical.
Returns
true if axis is vertical, false - overwise
Definition at line 66 of file axis.h.
Referenced by IsHorizontal().
virtual bool Axis::IsVisible (double value) virtual
Checks whether data value is visible.
Parameters
value value in data space
Returns
true if data value is visible
Reimplemented in AxisShare, and LogarithmicNumberAxis.
void Axis::SetMajorGridlinePen (const wxPen & pen) inline
Sets the pen to be used for drawing major gridlines.
A major gridline is a gridline that is associated with a major axis label.
Parameters
majorGridlinePen The pen to be used to draw major gridlines on this axis.
Definition at line 93 of file axis.h.
void Axis::SetMargins (wxCoord marginMin, wxCoord marginMax)
Sets minimal/maximal margins for axis.
Eg bottom/top for vertical axes, left/right for horizontal.
Parameters
marginMin new minimal margin
marginMax new maximal margin
Referenced by IsHorizontal().
void Axis::SetMinorGridlinePen (const wxPen & pen) inline
Sets the pen to be used for drawing minor gridlines.
A minor gridline is a gridline that is associated with a minor axis label, i.e. any label that is not a major axis label.
Parameters
minorGridlinePen The pen to be used to draw minor gridlines on this axis.
Definition at line 103 of file axis.h.
void Axis::SetUseWindow (bool useWin) inline
Sets whether to use window.
Parameters
useWin true to use window
Definition at line 191 of file axis.h.
void Axis::SetWindow (double winPos, double winWidth) inline
Sets window params (position and width).
Window params are in data space.
Parameters
winPos new window position
winWidth new window width
Definition at line 203 of file axis.h.
References IntersectsWindow().
Referenced by SetWindowPosition(), and SetWindowWidth().
void Axis::SetWindowPosition (double winPos) inline
Sets window position.
Window position is in data space.
Parameters
winPos new window position
Definition at line 173 of file axis.h.
References SetWindow().
void Axis::SetWindowWidth (double winWidth) inline
Sets window width.
Window width is in data space.
Parameters
winWidth new window width
Definition at line 155 of file axis.h.
References SetWindow().
virtual double Axis::ToData (wxDC & dc, int minCoord, int gRange, wxCoord g) virtual
Transforms coordinate from graphics space to data space.
Parameters
dc device context
minCoord minimal graphics space coordinate
gRange graphics space range
value value in data space
Returns
coordinate in data space
Reimplemented in AxisShare, LogarithmicNumberAxis, and CompDateAxis.
virtual wxCoord Axis::ToGraphics (wxDC & dc, int minCoord, int gRange, double value) virtual
Transforms coordinate from data space to graphics space.
Parameters
dc device context
minCoord minimal graphics space coordinate
gRange graphics space range
value value in data space
Returns
value in graphics space
Reimplemented in AxisShare, CompDateAxis, and LogarithmicNumberAxis.
The documentation for this class was generated from the following file:
include/wx/axis/axis.h